apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.apitanga/v1alpha1",
          "kind": "LaceworkAgent",
          "metadata": {
            "name": "laceworkagent-sample"
          },
          "spec": {
            "daemonset": {
              "affinity": {
                "nodeAffinity": {
                  "requiredDuringSchedulingIgnoredDuringExecution": {
                    "nodeSelectorTerms": [
                      {
                        "matchExpressions": [
                          {
                            "key": "kubernetes.io/arch",
                            "operator": "In",
                            "values": [
                              "amd64",
                              "arm64"
                            ]
                          },
                          {
                            "key": "kubernetes.io/os",
                            "operator": "In",
                            "values": [
                              "linux"
                            ]
                          }
                        ]
                      }
                    ]
                  }
                }
              },
              "updateStrategy": {
                "type": "RollingUpdate"
              }
            },
            "image": {
              "pullPolicy": "Always",
              "registry": "docker.io",
              "repository": "lacework/datacollector",
              "tag": "5.5.0"
            },
            "laceworkConfig": {
              "accessToken": null,
              "annotations": {},
              "autoUpgrade": "enable",
              "env": null,
              "fim": {
                "coolingPeriod": null,
                "crawlInterval": null,
                "enable": true,
                "fileIgnore": [],
                "filePath": [],
                "noAtime": null,
                "runAt": null
              },
              "kubernetesCluster": null,
              "labels": {},
              "proxyUrl": null,
              "serverUrl": "https://api.lacework.net",
              "stdoutLogging": true
            },
            "priorityClassName": null,
            "resources": {
              "limits": {
                "cpu": "500m",
                "memory": "1450Mi"
              },
              "requests": {
                "cpu": "200m",
                "memory": "512Mi"
              }
            },
            "tolerations": [
              {
                "effect": "NoSchedule",
                "key": "node-role.kubernetes.io/master"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: lacework-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: LaceworkAgent
      name: laceworkagents.charts.apitanga
      version: v1alpha1
  description: The Lacework Agent Operator deploys the Lacework Datacollector in a
    Kubernetes cluster. Lacework is the data-driven security platform for the cloud.
    The Lacework Polygraph Data Platform automates cloud security at scale so our
    customers can innovate with speed and safety.
  displayName: lacework-agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - charts.apitanga
          resources:
          - laceworkagents
          - laceworkagents/status
          - laceworkagents/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: lacework-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: lacework-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=lacework-operator
                image: dockerhub.io/apitanga/lacework:v1.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: lacework-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: lacework-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - security
  - cloud
  links:
  - name: Lacework Operator
    url: https://lacework-operator.domain
  maturity: alpha
  provider:
    name: Lacework
    url: lacework.com
  version: 0.0.1
