# permissions for end users to edit laceworkagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laceworkagent-editor-role
rules:
- apiGroups:
  - charts.apitanga
  resources:
  - laceworkagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.apitanga
  resources:
  - laceworkagents/status
  verbs:
  - get
