# permissions for end users to view laceworkagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laceworkagent-viewer-role
rules:
- apiGroups:
  - charts.apitanga
  resources:
  - laceworkagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.apitanga
  resources:
  - laceworkagents/status
  verbs:
  - get
