apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: lacework-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: The Lacework Agent Operator deploys the Lacework Datacollector in a
    Kubernetes cluster. Lacework is the data-driven security platform for the cloud.
    The Lacework Polygraph Data Platform automates cloud security at scale so our
    customers can innovate with speed and safety.
  displayName: lacework-agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - security
  - cloud
  links:
  - name: Lacework Operator
    url: https://lacework-operator.domain
  maturity: alpha
  provider:
    name: Lacework
    url: lacework.com
  version: 0.0.0
